package com.dc.test;

public class MyTest2 {

	public static void main(String[] args) {
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('330200','宁波市',11);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('330300','温州市',11);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('330400','嘉兴市',11);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('330500','湖州市',11);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('330600','绍兴市',11);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('330700','金华市',11);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('330800','衢州市',11);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('330900','舟山市',11);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('331000','台州市',11);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('331100','丽水市',11);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('340100','合肥市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('340200','芜湖市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('340300','蚌埠市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('340400','淮南市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('340500','马鞍山市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('340600','淮北市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('340700','铜陵市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('340800','安庆市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('341000','黄山市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('341100','滁州市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('341200','阜阳市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('341300','宿州市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('341400','巢湖市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('341500','六安市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('341600','亳州市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('341700','池州市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('341800','宣城市',12);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('350100','福州市',13);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('350200','厦门市',13);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('350300','莆田市',13);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('350400','三明市',13);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('350500','泉州市',13);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('350600','漳州市',13);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('350700','南平市',13);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('350800','龙岩市',13);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('350900','宁德市',13);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('360100','南昌市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('360200','景德镇市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('360300','萍乡市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('360400','九江市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('360500','新余市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('360600','鹰潭市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('360700','赣州市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('360800','吉安市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('360900','宜春市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('361000','抚州市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('361100','上饶市',14);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('370100','济南市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('370200','青岛市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('370300','淄博市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('370400','枣庄市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('370500','东营市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('370600','烟台市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('370700','潍坊市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('370800','济宁市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('370900','泰安市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('371000','威海市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('371100','日照市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('371200','莱芜市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('371300','临沂市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('371400','德州市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('371500','聊城市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('371600','滨州市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('371700','菏泽市',15);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('410100','郑州市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('410200','开封市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('410300','洛阳市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('410400','平顶山市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('410500','安阳市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('410600','鹤壁市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('410700','新乡市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('410800','焦作市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('410900','濮阳市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('411000','许昌市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('411100','漯河市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('411200','三门峡市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('411300','南阳市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('411400','商丘市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('411500','信阳市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('411600','周口市',16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('411700','驻马店市' ,16);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('420100','武汉市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('420200','黄石市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('420300','十堰市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('420500','宜昌市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('420600','襄樊市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('420700','鄂州市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('420800','荆门市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('420900','孝感市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('421000','荆州市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('421100','黄冈市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('421200','咸宁市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('421300','随州市',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('422800','恩施土家族苗族自治州',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('429000','省直辖行政单位',17);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('430100','长沙市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('430200','株洲市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('430300','湘潭市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('430400','衡阳市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('430500','邵阳市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('430600','岳阳市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('430700','常德市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('430800','张家界市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('430900','益阳市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('431000','郴州市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('431100','永州市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('431200','怀化市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('431300','娄底市',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('433100','湘西土家族苗族自治州',18);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('440100','广州市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('440200','韶关市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('440300','深圳市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('440400','珠海市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('440500','汕头市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('440600','佛山市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('440700','江门市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('440800','湛江市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('440900','茂名市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('441200','肇庆市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('441300','惠州市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('441400','梅州市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('441500','汕尾市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('441600','河源市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('441700','阳江市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('441800','清远市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('441900','东莞市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('442000','中山市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('445100','潮州市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('445200','揭阳市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('445300','云浮市',19);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('450100','南宁市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('450200','柳州市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('450300','桂林市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('450400','梧州市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('450500','北海市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('450600','防城港市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('450700','钦州市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('450800','贵港市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('450900','玉林市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('451000','百色市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('451100','贺州市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('451200','河池市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('451300','来宾市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('451400','崇左市',20);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('460100','海口市',21);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('460200','三亚市',21);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('469000','省直辖县级行政单位',21);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('500100','市辖区',22);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('510100','成都市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('510300','自贡市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('510400','攀枝花市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('510500','泸州市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('510600','德阳市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('510700','绵阳市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('510800','广元市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('510900','遂宁市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('511000','内江市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('511100','乐山市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('511300','南充市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('511400','眉山市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('511500','宜宾市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('511600','广安市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('511700','达州市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('511800','雅安市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('511900','巴中市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('512000','资阳市',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('513200','阿坝藏族羌族自治州',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('513300','甘孜藏族自治州',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('513400','凉山彝族自治州',23);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('520100','贵阳市',31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('520200','六盘水市',31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('520300','遵义市',31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('520400','安顺市'   ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('522200','铜仁地区'    ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('522300','黔西南布依族苗族自治州'  ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('522400','毕节地区'   ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('522600','黔东南苗族侗族自治州' ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('522700','黔南布依族苗族自治州',31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('530100','昆明市',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('530300','曲靖市',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('530400','玉溪市',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('530500','保山市',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('530600','昭通市',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('530700','丽江市',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('530800','思茅市',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('530900','临沧市',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('532300','楚雄彝族自治州',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('532500','红河哈尼族彝族自治州' ,25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('532600','文山壮族苗族自治州' ,25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('532800','西双版纳傣族自治州' ,25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('532900','大理白族自治州'  ,25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('533100','德宏傣族景颇族自治州' ,25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('533300','怒江傈僳族自治州',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('533400','迪庆藏族自治州',25);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('540100','拉萨市',26);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('542100','昌都地区'  ,26);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('542200','山南地区'  ,26);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('542300','日喀则地区'  ,26);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('542400','那曲地区',26);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('542500','阿里地区',26);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('542600','林芝地区',26);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('610100','西安市',27);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('610200','铜川市',27);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('610300','宝鸡市',27);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('610400','咸阳市',27);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('610500','渭南市',27);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('610600','延安市',27);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('610700','汉中市',27);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('610800','榆林市',27);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('610900','安康市',27);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('611000','商洛市',27);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('620100','兰州市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('620200','嘉峪关市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('620300','金昌市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('620400','白银市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('620500','天水市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('620600','武威市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('620700','张掖市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('620800','平凉市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('620900','酒泉市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('621000','庆阳市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('621100','定西市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('621200','陇南市',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('622900','临夏回族自治州',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('623000','甘南藏族自治州',28);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('630100','西宁市'        ,29);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('632100','海东地区'      ,29);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('632200','海北藏族自治州',29);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('632300','黄南藏族自治州',29);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('632500','海南藏族自治州',29);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('632600','果洛藏族自治州',29);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('632700','玉树藏族自治州',29);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('632800','海西蒙古族藏族自治州' ,29);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('640100','银川市'               ,30);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('640200','石嘴山市'             ,30);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('640300','吴忠市'               ,30);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('640400','固原市'               ,30);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('640500','中卫市'               ,30);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('650100','乌鲁木齐市'           ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('650200','克拉玛依市'           ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('652100','吐鲁番地区'           ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('652200','哈密地区'             ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('652300','昌吉回族自治州'       ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('652700','博尔塔拉蒙古自治州'   ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('652800','巴音郭楞蒙古自治州'   ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('652900','阿克苏地区'           ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('653000','克孜勒苏柯尔克孜自治州',31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('653100','喀什地区'             ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('653200','和田地区'             ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('654000','伊犁哈萨克自治州'     ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('654200','塔城地区'             ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('654300','阿勒泰地区'           ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('659000','省直辖行政单位'       ,31);");
		System.out.println("INSERT INTO city (cityCode,cityName,provinceId) VALUES('000000','其他'        ,32);");
	}
}
